### ISSUE TITLE
Application Viewer

### ISSUE THREAD

**Issue by mbeierat** [refundable-tgm/web#1]
**What shall be implemented?**

A viewer for applications which directly opens when called using a permanent link providing the UID of the application (for example: `https://URL/viewer?uid=1234`). In addition when this viewer is called without an UID (for example: `https://URL/viewer`)  an input field should show up on the website where the UID can be entered. Then the viewer could forward the user to the viewer with the entered UID (for example: if `4321` is entered `https://URL/viewer?uid=4321`).

Of course if a permanent link is used or if just the finder part of the viewer is accessed the user has to be logged in to the system. If he is not, he should be prompted to do so and afterwards be forwarded to the previously accessed resource.

**Why is this needed?**

The library for generating PDF files explicitly lists support for QR codes. This could be used to easily implement a link to an application in the system onto a printed document in form of a QR code. The corresponding perma-link would be printed under the QR code. Then using this feature the complete application, the printed out document belongs to, can be viewed.

**Comment by ldehner** [comment]
view implemented in 22a95eab

**Comment by rfoster93** [comment]
Basic functionality added in 8b1601c
