### ISSUE TITLE
Radio Buttons bugging New application - Schulveranstaltung - Step 2 

### ISSUE THREAD

**Issue by ldehner** [refundable-tgm/web#15]
![image](https://user-images.githubusercontent.com/28535268/103422985-84394e80-4ba4-11eb-9873-375f37ebc680.png)
ALL Radio Buttons are in the same group (also the radio buttons from other persons)

**Comment by rfoster93** [comment]
implemented in 781f649

**Comment by rfoster93** [comment]
implemented in 781f649
