### ISSUE TITLE
View position bugging New application - Schulveranstaltung - Step 2

### ISSUE THREAD

**Issue by ldehner** [refundable-tgm/web#19]
If you press "weiter" and reach the settings for the escort personal, the position of the website isnt on the top, its somewhere in the middle 
![image](https://user-images.githubusercontent.com/28535268/103439637-f2caea80-4c3e-11eb-9590-ef2f31f26510.png)

**Comment by rfoster93** [comment]
implemented in 781f649

**Comment by rfoster93** [comment]
implemented in 781f649
