### ISSUE TITLE
Create "Other Cuase" Application dynamic "other" field

### ISSUE THREAD

**Issue by ldehner** [refundable-tgm/web#22]
Only show "Sonstiger Grund" if "Sonstiges" is selected at the "Grund" field.
![image](https://user-images.githubusercontent.com/28535268/103440122-5c4cf800-4c43-11eb-8f90-f2082b30602c.png)

**Comment by rfoster93** [comment]
implemented in 781f649

**Comment by rfoster93** [comment]
implemented in 781f649
