### ISSUE TITLE
Current applications quick info not working

### ISSUE THREAD

**Issue by ldehner** [refundable-tgm/web#28]
Put the steps of the application (AV - applied/not applied) usw. and their status in the modal
![image](https://user-images.githubusercontent.com/28535268/103445077-12c6d200-4c70-11eb-9d58-c57197b6e83a.png)
![image](https://user-images.githubusercontent.com/28535268/103445080-1fe3c100-4c70-11eb-81fe-3695820ec56f.png)

**Comment by rfoster93** [comment]
fixed bug from 01ce24c in a806700

**Comment by rfoster93** [comment]
Implemented in d4f05ec
