### ISSUE TITLE
Make application view dynamic

### ISSUE THREAD

**Issue by ldehner** [refundable-tgm/web#35]
Green: Add Application Title
Red: Add document names (Varies according to application type)
Yellow: Add The formulars of the document (components available in applicationViewComponents folder)
Cyan: Save edited information
"Antrag schließen" Modal: If the close button in the modal is pressed set the state of the application on closed
![image](https://user-images.githubusercontent.com/28535268/103446073-bd90bd80-4c7b-11eb-8c73-81e9d29bab68.png)

**Comment by rfoster93** [comment]
Started work in 516ce8c

**Comment by ldehner** [comment]
Update @rfoster93:

### General
**_Schulveranstaltung_:**
- Don't forget to set the application title at the top
- Only show the _Allgemeine Infos_ application to the leader
- Only show the leader his own _Begleitformular_ not the applications of the other escorts
- Only let the user change data of a specific application if the application was denied
- Link the _PDF öffnen_ buttons with the specific application and the browser standard pdf viewer

### Progressbar
- Change the Progress bar depending on the application
- Change the status of the progressbar as the status of the application changes

**Steps for the leader of a _Schulveranstaltung_:**
1. Dienstreiseantrag eingereicht
2. Von Begleitern bestätigt
3. Von AV akzeptiert
4. Rechnungen eingereicht
5. Von Rechnungsstelle akzeptiert

**Steps for an escort of a _Schulveranstaltung_:**
1. Von Ihnen bestätigt
2. Anträge eingereicht
3. Von AV akzeptiert
4. Rechnungen eingereicht
5. Von Rechnungsstelle akzeptiert

**Steps for _Fortbildung/Dienstauftrag_:**
1. Anträge eingereicht
2. Von AV akzeptiert
3. Rechnungen eingereicht
4. Von Rechnungsstelle akzeptiert

**Steps for _Abwesenheitsformular_:**
1. Anträge eingereicht
2. Von AV akzeptiert

**Comment by rfoster93** [comment]
ProgressBar functionality implemented in caadfa3 and ffa1c99

**Comment by rfoster93** [comment]
Fixed errors of table in 7ef746f and added PDF function

**Comment by rfoster93** [comment]
started work on main functionality of ApplicationView in ef1109c

**Comment by rfoster93** [comment]
ProgressBar functionality changed in bc8a535

**Comment by rfoster93** [comment]
Implemented fully in 0d0f40d
