### ISSUE TITLE
Dashboard admin button functionality

### ISSUE THREAD

**Issue by ldehner** [refundable-tgm/web#37]
Show admin dashboard if admin button is clicked.
**Watch out that you also implement this function on mobile view!**
Admin Component in:
![image](https://user-images.githubusercontent.com/28535268/103447298-74476a80-4c89-11eb-8519-3b56c2ba7d57.png)

![image](https://user-images.githubusercontent.com/28535268/103447280-39453700-4c89-11eb-8833-bf30297437f2.png)

**Comment by rfoster93** [comment]
Implemented in 67da06c
