### ISSUE TITLE
Add functionality to admin home view

### ISSUE THREAD

**Issue by ldehner** [refundable-tgm/web#41]
Red: Add functionality to the header buttons
Orange: Add functionality to the print button (open the selected pdfs in new tab, standard pdf viewer)
Green: Change color (variant) of badges, for the different types of applications, (look at https://bootstrap-vue.org/docs/components/badge)
Cyan: Change color (variant) of badges, for the different states of the applications, (look at https://bootstrap-vue.org/docs/components/badge)
Pink: Redirect to the specific ApplicationAdminView if button is pressed
![image](https://user-images.githubusercontent.com/28535268/103479418-c5f90d80-4dcd-11eb-8599-f0f370d2ee68.png)

**Comment by rfoster93** [comment]
Red implemented in 14ce9c6

**Comment by rfoster93** [comment]
Pink implemented in cda91a0

Green and Cyan implemented in def3007

**Comment by rfoster93** [comment]
Started work on Orange in 0681a16

**Comment by rfoster93** [comment]
Implemented Orange in 453fc76
