### ISSUE TITLE
make Travelbill dynamic

### ISSUE THREAD

**Issue by ldehner** [refundable-tgm/web#53]
**ToDo:**
Table:
![image](https://user-images.githubusercontent.com/28535268/109526307-b38c0f00-7ab2-11eb-8931-c18a2c54c1fc.png)
&fix table headings

Checkboxes:
Only show fields if specific checkbox is checked
![image](https://user-images.githubusercontent.com/28535268/109527320-cbb05e00-7ab3-11eb-8883-eb869277e1c7.png)

**Official Document BSP:**
![image](https://user-images.githubusercontent.com/28535268/109526564-fbab3180-7ab2-11eb-9b9b-24cb20d52f8f.png)

**Comment by rfoster93** [comment]
Checkboxes implemented in 039a2ce

**Comment by rfoster93** [comment]
fixed bug with with of table in b3dd5e1

claculation of sum implemented in e03f1d4

data sending between Escort and TravelBill finished in 9a4dde2

**Comment by rfoster93** [comment]
Implemented fully in 0d0f40d
